let efectivo = 3000
alert("De compras en la verduleria, llevando $3000 en efectivo. Selecciona cuantos kg llevaras💸")
let papa = Number(prompt("Papa $200xKg"))
let cebolla = Number(prompt("Cebolla$500xKg"))
let zanahoria = Number(prompt("Zanahoria $350xKg"))
let acelga = Number(prompt("Acelga $300xKg"))
let brocoli = Number(prompt("Brocoli $600xKg"))
let tomate = Number(prompt("Tomate $250xKg"))
let lechuga = Number(prompt("Lechuga $800xKg"))
let zapallo = Number(prompt("Zapallo $120xKg"))
let manzana = Number(prompt("Manzana $350xKg"))
let pera = Number(prompt("Pera $400xKg"))
let banana = Number(prompt("Banana $350xKg"))
let uva = Number(prompt("Uva $450xKg"))
let pago = efectivo - ((papa * 200) + (cebolla * 500) + (zanahoria * 350) + (acelga * 300) + (brocoli * 600) + (tomate * 250) + (lechuga * 800) + (zapallo * 120) + (manzana * 350) + (pera * 400) + (banana * 350) + (uva * 450))
alert("Veamos si te alcanzo para llevar todo lo del carrito😁")
alert("$" + pago)
